"""This file was generated by xsdata, v24.4, on 2024-04-22 17:48:31

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from oaipmh_scythe.models.oai_pmh.models import (
    About,
    DeletedRecord,
    Description,
    GetRecord,
    Granularity,
    Header,
    Identify,
    ListIdentifiers,
    ListMetadataFormats,
    ListRecords,
    ListSets,
    Metadata,
    MetadataFormat,
    OaiPmh,
    OaiPmherror,
    OaiPmherrorcode,
    OaiPmhtype,
    ProtocolVersion,
    Record,
    Request,
    ResumptionToken,
    Set,
    Status,
    Verb,
)

__all__ = [
    "GetRecord",
    "Identify",
    "ListIdentifiers",
    "ListMetadataFormats",
    "ListRecords",
    "ListSets",
    "OaiPmh",
    "OaiPmherror",
    "OaiPmherrorcode",
    "OaiPmhtype",
    "About",
    "DeletedRecord",
    "Description",
    "Granularity",
    "Header",
    "MetadataFormat",
    "Metadata",
    "ProtocolVersion",
    "Record",
    "Request",
    "ResumptionToken",
    "Set",
    "Status",
    "Verb",
]
