"""This file was generated by xsdata, v24.4, on 2024-04-23 15:41:50

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from oaipmh_scythe.models.marcxml.models import (
    Collection,
    CollectionType,
    ControlFieldType,
    DataFieldType,
    LeaderFieldType,
    Record,
    RecordType,
    RecordTypeType,
    SubfieldatafieldType,
)

__all__ = [
    "Collection",
    "CollectionType",
    "ControlFieldType",
    "DataFieldType",
    "LeaderFieldType",
    "Record",
    "RecordType",
    "RecordTypeType",
    "SubfieldatafieldType",
]
