"""This file was generated by xsdata, v24.4, on 2024-04-23 15:41:50

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum

__NAMESPACE__ = "http://www.loc.gov/MARC21/slim"


@dataclass(slots=True)
class ControlFieldType:
    """MARC21 Fields 001-009."""

    class Meta:
        name = "controlFieldType"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "white_space": "preserve",
        },
    )
    id: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    tag: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "white_space": "preserve",
            "pattern": r"00[1-9A-Za-z]{1}",
        },
    )


@dataclass(slots=True)
class LeaderFieldType:
    """MARC21 Leader, 24 bytes."""

    class Meta:
        name = "leaderFieldType"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "white_space": "preserve",
            "pattern": r"[\d ]{5}[\dA-Za-z ]{1}[\dA-Za-z]{1}[\dA-Za-z ]{3}(2| )(2| )[\d ]{5}[\dA-Za-z ]{3}(4500|    )",
        },
    )
    id: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


class RecordTypeType(Enum):
    BIBLIOGRAPHIC = "Bibliographic"
    AUTHORITY = "Authority"
    HOLDINGS = "Holdings"
    CLASSIFICATION = "Classification"
    COMMUNITY = "Community"


@dataclass(slots=True)
class SubfieldatafieldType:
    class Meta:
        name = "subfieldatafieldType"

    value: str = field(
        default="",
        metadata={
            "required": True,
            "white_space": "preserve",
        },
    )
    id: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    code: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[\dA-Za-z!\"#$%&'()*+,-./:;<=>?{}_^`~\[\]\\]{1}",
        },
    )


@dataclass(slots=True)
class DataFieldType:
    """MARC21 Variable Data Fields 010-999."""

    class Meta:
        name = "dataFieldType"

    subfield: list[SubfieldatafieldType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.loc.gov/MARC21/slim",
            "min_occurs": 1,
        },
    )
    id: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )
    tag: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "white_space": "preserve",
            "pattern": r"(0([1-9A-Z][0-9A-Z])|0([1-9a-z][0-9a-z]))|(([1-9A-Z][0-9A-Z]{2})|([1-9a-z][0-9a-z]{2}))",
        },
    )
    ind1: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[\da-z ]{1}",
        },
    )
    ind2: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
            "required": True,
            "white_space": "preserve",
            "pattern": r"[\da-z ]{1}",
        },
    )


@dataclass(slots=True)
class RecordType:
    class Meta:
        name = "recordType"

    leader: None | LeaderFieldType = field(
        default=None,
        metadata={
            "type": "Element",
            "namespace": "http://www.loc.gov/MARC21/slim",
        },
    )
    controlfield: list[ControlFieldType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.loc.gov/MARC21/slim",
        },
    )
    datafield: list[DataFieldType] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.loc.gov/MARC21/slim",
        },
    )
    type_value: None | RecordTypeType = field(
        default=None,
        metadata={
            "name": "type",
            "type": "Attribute",
        },
    )
    id: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass(slots=True)
class Record(RecordType):
    """Record is a top level container element for all of the field elements which compose the record."""

    class Meta:
        name = "record"
        nillable = True
        namespace = "http://www.loc.gov/MARC21/slim"


@dataclass(slots=True)
class CollectionType:
    class Meta:
        name = "collectionType"

    record: list[Record] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://www.loc.gov/MARC21/slim",
            "nillable": True,
        },
    )
    id: None | str = field(
        default=None,
        metadata={
            "type": "Attribute",
        },
    )


@dataclass(slots=True)
class Collection(CollectionType):
    """Collection is a top level container element for 0 or many records."""

    class Meta:
        name = "collection"
        nillable = True
        namespace = "http://www.loc.gov/MARC21/slim"
