"""This file was generated by xsdata, v24.4, on 2024-04-21 17:47:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from oaipmh_scythe.models.oai_dc.models import (
    Contributor,
    Coverage,
    Creator,
    Date,
    Dc,
    Description,
    ElementType,
    Format,
    Identifier,
    Language,
    LangValue,
    OaiDcType,
    Publisher,
    Relation,
    Rights,
    Source,
    Subject,
    Title,
    TypeType,
)

__all__ = [
    "Contributor",
    "Coverage",
    "Creator",
    "Date",
    "Dc",
    "Description",
    "ElementType",
    "Format",
    "Identifier",
    "LangValue",
    "Language",
    "OaiDcType",
    "Publisher",
    "Relation",
    "Rights",
    "Source",
    "Subject",
    "Title",
    "TypeType",
]
