"""This file was generated by xsdata, v24.4, on 2024-04-21 17:47:18

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum


class LangValue(Enum):
    VALUE = ""


@dataclass(slots=True)
class ElementType:
    class Meta:
        name = "elementType"
        target_namespace = "http://purl.org/dc/elements/1.1/"

    value: str = field(
        default="",
        metadata={
            "required": True,
        },
    )
    lang: None | str | LangValue = field(
        default=None,
        metadata={
            "type": "Attribute",
            "namespace": "http://www.w3.org/XML/1998/namespace",
        },
    )


@dataclass(slots=True)
class Contributor(ElementType):
    class Meta:
        name = "contributor"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Coverage(ElementType):
    class Meta:
        name = "coverage"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Creator(ElementType):
    class Meta:
        name = "creator"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Date(ElementType):
    class Meta:
        name = "date"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Description(ElementType):
    class Meta:
        name = "description"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Format(ElementType):
    class Meta:
        name = "format"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Identifier(ElementType):
    class Meta:
        name = "identifier"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Language(ElementType):
    class Meta:
        name = "language"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Publisher(ElementType):
    class Meta:
        name = "publisher"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Relation(ElementType):
    class Meta:
        name = "relation"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Rights(ElementType):
    class Meta:
        name = "rights"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Source(ElementType):
    class Meta:
        name = "source"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Subject(ElementType):
    class Meta:
        name = "subject"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class Title(ElementType):
    class Meta:
        name = "title"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class TypeType(ElementType):
    class Meta:
        name = "type"
        namespace = "http://purl.org/dc/elements/1.1/"


@dataclass(slots=True)
class OaiDcType:
    class Meta:
        name = "oai_dcType"
        target_namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/"

    title: list[Title] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    creator: list[Creator] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    subject: list[Subject] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    description: list[Description] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    publisher: list[Publisher] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    contributor: list[Contributor] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    date: list[Date] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    type_value: list[TypeType] = field(
        default_factory=list,
        metadata={
            "name": "type",
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    format: list[Format] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    identifier: list[Identifier] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    source: list[Source] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    language: list[Language] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    relation: list[Relation] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    coverage: list[Coverage] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )
    rights: list[Rights] = field(
        default_factory=list,
        metadata={
            "type": "Element",
            "namespace": "http://purl.org/dc/elements/1.1/",
        },
    )


@dataclass(slots=True)
class Dc(OaiDcType):
    class Meta:
        name = "dc"
        namespace = "http://www.openarchives.org/OAI/2.0/oai_dc/"
