"""This file was generated by xsdata, v24.4, on 2024-04-21 17:40:55

Generator: DataclassGenerator
See: https://xsdata.readthedocs.io/
"""

from oaipmh_scythe.models.datacite.models import (
    Affiliation,
    Box,
    ContributorType,
    DateType,
    DescriptionType,
    FunderIdentifierType,
    LangValue,
    NameIdentifier,
    NameType,
    NumberType,
    Point,
    RelatedIdentifierType,
    RelationType,
    Resource,
    ResourceType,
    TitleType,
)

__all__ = [
    "Affiliation",
    "Box",
    "ContributorType",
    "DateType",
    "DescriptionType",
    "FunderIdentifierType",
    "LangValue",
    "NameIdentifier",
    "NameType",
    "NumberType",
    "Point",
    "RelatedIdentifierType",
    "RelationType",
    "Resource",
    "ResourceType",
    "TitleType",
]
